# Generated by Django 2.2.6 on 2021-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210415_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите картинку к посту', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
